In [3]:
import re
import os
import pandas as pd

In [29]:
df = pd.read_excel('re_investment_tracker.xlsm', sheet_name='investment_tracker', skiprows=9)

In [31]:
df = df.rename(columns={'loans_position':'loan_position'})

In [6]:
tape_noble = pd.read_csv('tapes/tape_noble-20200504.csv')
tape_patch = pd.read_csv('tapes/tape_patch-20200504.csv')
tape_ppm = pd.read_csv('tapes/tape_ppm-20200504.csv')

In [ ]:
def clean_tape(tape):
    tape_filename = 'tapes/tape_ppm-20200504.csv'
    
    tape.columns = tape.columns.str.strip()
    tape.columns = tape.columns.str.replace(' ', '_')
    tape.columns = tape.columns.str.lower()
    
    #lender
    lender = re.search('tapes/tape_(.*)-', tape_filename)
    lender = lender.group(1)
    
    tape['lender'] = lender
    
    #loan_id
    cols = ['loan_number', 'loan_id', 'loan_#']
    for col in cols:
        tape = tape.rename(columns={col:'loan_id'})
    
    #prop_address
    
    #prop_city
    
    #prop_state
    
    #prop_zip
    
    #prop_aiv
    cols = ['estimated_as-is_value', 'as-is_value', 'total_cost', 'market_value']
    for col in cols:
        tape = tape.rename(columns={col:'prop_aiv'})
    
    #prop_arv
    cols = ['']
    for col in cols:
        tape = tape.rename(columns={col:'prop_arv'})
        
    #prop_type
    cols = ['property_type']
    for col in cols:
        tape = tape.rename(columns={col:'prop_type'})
    
    #prop_cost_basis
    cols = ['total_purchase_price', 'total_cost']
    for col in cols:
        tape = tape.rename(columns={col:'prop_cost_basis'})
    
    #bor_name
    cols = ['primary_guarantor_name', 'borrowing_entity']
    for col in cols:
        tape = tape.rename(columns={col:'bor_name'})
    
    #bor_address
    cols = ['']
    for col in cols:
        tape = tape.rename(columns={col:'bor_address'})
    
    #bor_city
    cols = ['']
    for col in cols:
        tape = tape.rename(columns={col:'bor_city'})
    
    #bor_state
    cols = ['']
    for col in cols:
        tape = tape.rename(columns={col:'bor_state'})
        
    #bor_zip
    cols = ['']
    for col in cols:
        tape = tape.rename(columns={col:'bor_zip'})
    
    #bor_fico
    cols = ['borrower_fico', 'credit']
    for col in cols:
        tape = tape.rename(columns={col:'bor_fico'})
    
    #bor_liq
    cols = ['']
    for col in cols:
        tape = tape.rename(columns={col:'bor_liq'})
    
    #loan_orig_date
    cols = ['origination_date', 'close']
    for col in cols:
        tape = tape.rename(columns={col:'loan_orig_date'})    
    
    #loan_mat_date
    cols = ['maturity']
    for col in cols:
        tape = tape.rename(columns={col:'loan_mat_date'})    
    
    #loan_term
    cols = ['loan_term', 'term']
    for col in cols:
        tape = tape.rename(columns={col:'loan_term'})    
    
    #loan_opb
    cols = ['loan_amount', 'original_loan_amount']
    for col in cols:
        tape = tape.rename(columns={col:'loan_opb'})
    
    #loan_upb
    cols = ['current_balance']
    for col in cols:
        tape = tape.rename(columns={col:'loan_upb'})    
    
    #loan_position
    cols = ['lien_status']
    for col in cols:
        tape = tape.rename(columns={col:'loan_position'})
    
    #loan_ltc_ratio_stated
    cols = ['ltc']
    for col in cols:
        tape = tape.rename(columns={col:'loan_ltc_ratio_stated'})
    
    #loan_ltaiv_ratio_stated
    cols = ['']
    for col in cols:
        tape = tape.rename(columns={col:'loan_ltaiv_ratio_stated'})
    
    #loan_ltarv_ratio_stated
    cols = ['']
    for col in cols:
        tape = tape.rename(columns={col:'loan_ltarv_ratio_stated'})
    
    #loan_exit_strat
    cols = ['']
    for col in cols:
        tape = tape.rename(columns={col:'loan_exit_strat'})
    
    #loan_type
    cols = ['']
    for col in cols:
        tape = tape.rename(columns={col:'loan_type'})
    
    #draw_requested
    cols = ['']
    for col in cols:
        tape = tape.rename(columns={col:'draw_requested'})
    
    #draw_total
    cols = ['']
    for col in cols:
        tape = tape.rename(columns={col:'draw_total'})
    
    #draw_remaining
    cols = ['']
    for col in cols:
        tape = tape.rename(columns={col:'draw_remaining'})
    
    #draw_disbursed
    cols = ['']
    for col in cols:
        tape = tape.rename(columns={col:'draw_disbursed'})
    
    return tape

In [54]:
tapes = [tape_noble, tape_patch, tape_ppm]

In [56]:
for i in range(len(tapes)):
    tapes[i] = clean_tape(tapes[i])

In [57]:
tape_noble.head()

,loan_#,borrowing_entity,address,county,city,state,zip,origination_date,loan_amount,current_balance,current_rehab_amount,next_due_payment,arv,total_cost,ltv,ltc,rate,credit,lender
0,3888.0,"Monty C Investments, LLC",1009 Romeria 2,Travis,Austin,TX,78757.0,4/22/2019,"$336,800.00","$314,000.00","$22,800.00",5/1/2020,"$482,000.00","$361,094.00",69.88%,93.27%,12.00%,746/769,ppm
1,3893.0,"Waterloo City Construction, LLC",6503 Felix B,Travis,Austin,TX,78741.0,5/7/2019,"$462,000.00","$389,000.00","$73,000.00",5/1/2020,"$660,000.00","$509,509.00",70.00%,90.68%,12.50%,730,ppm
2,3988.0,"Community Development Group, LLC",711 Whitney A,Harris,Houston,TX,77022.0,6/23/2019,"$3,906,100.00","$736,200.00","$3,169,900.00",5/1/2020,"$5,730,000.00","$4,524,515.00",68.17%,86.33%,12.50%,"709, 743, 738, 559",ppm
3,4034.0,"CONSIGLIA ENTERPRISES, LLC",110 W 55th,Travis,Austin,TX,78751.0,7/17/2019,"$306,600.00","$173,000.00","$133,600.00",5/1/2020,"$438,000.00","$353,864.00",70.00%,86.64%,11.00%,703,ppm
4,3931.0,"Triple B Multi-Solutions, LLC",215 Bundy,Bexar,San Antonio,TX,78231.0,7/19/2019,"$103,600.00","$65,000.00","$38,600.00",5/1/2020,"$148,000.00","$129,140.00",70.00%,80.22%,12.50%,699,ppm

In [47]:
tape_patch.head()

,loan_id,loan_status,primary_property_address,address,city,state,zip,product_type,ltv,arv,ltc,loan_amount,disbursed_at_closing,total_renovation_budget,primary_guarantor_name,property_type,funding_source,interest_rate,title_order_date,title_received,loan_officer:_full_name,loan_term,appraisal_received,estimated_as-is_value,estimated_after_renovation_value,as-is_value,after_renovation_value,total_purchase_price,wire_sent_date,scheduled_closing_date,lender
0,76113,Q.C. REVIEW,"814 Steuben St., Pittsburgh, PA, 15220",814 Steuben St.,Pittsburgh,PA,15220,Residential - Refinance,NaN,NaN,NaN,"$311,000.00","$311,000.00",$0.00,Sterling Miles,NaN,NaN,11.00%,NaN,NaN,Steven Weinstock,12,NaN,"$620,700.00",$0.00,$0.00,$0.00,$0.00,NaN,4/20/2020,ppm
1,76114,Q.C. REVIEW,"105 Red Oak Dr.,, Vicksburg, MS, 39180",105 Red Oak Dr.,Vicksburg,MS,39180,Residential - Refinance,51.06%,NaN,NaN,"$257,000.00","$257,000.00",$0.00,Sterling Miles,NaN,Track,11.00%,NaN,NaN,Steven Weinstock,12,NaN,"$503,300.00",$0.00,$0.00,$0.00,$0.00,NaN,4/20/2020,ppm
2,76013,Q.C. REVIEW,"226 Polar Rock Rd. SW, Altanta, GA, 30315",226 Polar Rock Rd. SW,Altanta,GA,30315,Residential - Refinance,NaN,NaN,NaN,"$387,000.00","$387,000.00",$0.00,Sterling Miles,NaN,Track,11.00%,NaN,NaN,Steven Weinstock,12,NaN,"$774,900.00",$0.00,$0.00,$0.00,$0.00,NaN,4/20/2020,ppm
3,76112,Q.C. REVIEW,"410 Bank St., Leadwood, MA, 63653",410 Bank St.,Leadwood,MA,63653,Residential - Refinance,50.01%,NaN,NaN,"$290,000.00","$290,000.00",$0.00,Sterling Miles,NaN,Track,11.00%,NaN,NaN,Steven Weinstock,12,NaN,"$579,900.00",$0.00,$0.00,$0.00,$0.00,NaN,4/20/2020,ppm
4,76115,Q.C. REVIEW,"22711 State Highway 13, Glidden, WI, 54527",22711 State Highway 13,Glidden,WI,54527,Residential - Refinance,NaN,NaN,NaN,"$200,000.00","$200,000.00",$0.00,Sterling Miles,NaN,Track,11.00%,NaN,NaN,Steven Weinstock,12,NaN,"$400,400.00",$0.00,$0.00,$0.00,$0.00,NaN,4/20/2020,ppm

In [44]:
tape_ppm.head()

,property,active/paid_off_or_n/a,loan_number,multi-lender_y/n,lien_status,original_loan_amount,term,close,maturity,note_rate,sold_rate,ltv,serviced,bus/_cons,borrower_fico,market_value,payoff_date,actual_term_of_paid_off_loans,lender
0,"552 East Palmyra Avenue., Orange, CA 92866; 46...",Paid off,2016-1213,Y,2nd,"$1,371,000",11,1/12/2017,1/1/2018,9.90%,9.90%,66.60%,ppm,Cons,636,"$2,281,000.00",8/15/2018,19.33,ppm
1,"1069 Westridge Ave., Danville, CA 94526",Paid off,2016-1219,Y,1st,"$1,220,000",11,1/12/2017,1/1/2018,9.90%,9.90%,69.25%,PPM,Cons,690,"$1,762,000.00",8/19/2017,7.30,ppm
2,"165 Nymph Rd., Bolinas, CA 94924",Paid off,2017-0217,N,1st,"$558,000",11,3/6/2017,3/1/2018,8.99%,8.99%,72.00%,ppm,Cons,754,"$790,000.00",10/6/2017,7.13,ppm
3,"1617 Fernwood Dr., Oakland 94611; 218 Peppermi...",Paid off,2017-0303,Y,1st,"$1,600,000",11,3/17/2017,3/1/2018,9.50%,9.50%,72.00%,PPM,Cons,707,"$1,650,000.00",5/30/2017,2.47,ppm
4,"1401 Quesada Ave, San Francisco, CA 94124",Paid off,2017-0308,Y,1st,"$325,000",11,4/14/2017,4/1/2018,9.90%,9.50%,48.00%,ppm,con,565,"$682,000.00",6/23/2018,14.50,ppm